{"name": "test_login_courier_with_wrong_login_error_expected", "status": "passed", "steps": [{"name": "Проверка ошибки при неправильном заполнении поля login", "status": "passed", "steps": [{"name": "Авторизовать курьера", "status": "passed", "parameters": [{"name": "body", "value": "{'login': 'ninjaQA', 'password': '12345'}"}], "start": 1725462727088, "stop": 1725462727687}], "start": 1725462727088, "stop": 1725462727689}], "start": 1725462727087, "stop": 1725462727689, "uuid": "6c0dfd67-8c8d-4988-8fec-f8863b8739c9", "historyId": "4389fbf34a32353a62dcc5b20f174ec1", "testCaseId": "4389fbf34a32353a62dcc5b20f174ec1", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_login_error_expected", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Dolbobook"}, {"name": "thread", "value": "19956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}